version: "3.9"
   
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      - CLOUDINARY_API_KEY=171759724969595
      - CLOUDINARY_API_SECRET=12LboDYtu51IKMMLKYojyyNUQeE
      - CLOUDINARY_CLOUD_NAME=daryn06r2
      - DATABASE_URL='postgres://default:Utyxu15nKPEv@ep-dry-union-64351208-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb'