# Generated by Django 4.2.4 on 2023-10-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('profile_picture', models.TextField(blank=True, default='')),
                ('theme', models.CharField(default='light', max_length=20)),
            ],
        ),
    ]
